# Placeholders to be rewritten by launch file:
# - <entity> : Should be replaced by entity name: For example "robot".

- ros_topic_name: "odom"
  gz_topic_name: "/model/<entity>/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
# odom <-> base_link transform
- ros_topic_name: "tf"
  gz_topic_name: "/model/<entity>/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
# - ros_topic_name: "joint_states"
#   gz_topic_name: "/world/gazebo_world/model/<entity>/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS
- ros_topic_name: "imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
- ros_topic_name: "odometry/filtered"
  gz_topic_name: "/model/<entity>/odometry_filtered"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: ROS_TO_GZ
- ros_topic_name: "valves_cmd_mask"
  gz_topic_name: "/model/<entity>/valves_cmd_mask"
  ros_type_name: "std_msgs/msg/UInt32"
  gz_type_name: "gz.msgs.UInt32"
  direction: ROS_TO_GZ
