ekf_filter_node:
  ros__parameters:

    two_d_mode: true             # Set to true if you are using a 2D robot
    map_frame: map                  # Defaults to "map" if unspecifie
    odom_frame: odom                # Defaults to "odom" if unspecifie
    base_link_frame: base_link      # Defaults to "base_link" if unspec
    world_frame: odom               # Defaults to the value of odom_fr

    # Real odometry
    odom0: /odom
    # IMU
    imu0: /imu

    # [x_pos , y_pos , z_pos ,
    #  roll  , pitch , yaw ,
    #  x_vel , y_vel , z_vel ,
    #  rotl_vel, pitch_vel, yaw_vel,
    #  x_accel , y_accel , z_accel]

    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true, false,
                   false, false, true,
                   false, false, false]

    imu0_config:  [false, false, false,
                   false, false, true,
                   false, false, false,
                   false, false, true,
                   true,  false, false]
